### PR TITLE
Add a6d command

### PR DESCRIPTION
**Pull request by thetayloredman**
This fixes the a6d command

### CODE REVIEW

**Comment by wissehes** [comment]
I had it commented out, because I didn't have anything to put into it yet :/. But thanks for your PR

**Comment by thetayloredman** [comment]
I am going to add more to the command, don't merge yet

**Comment by thetayloredman** [comment]
There, I added command results. @TheChicken14

**Comment by thetayloredman** [comment]
Also, do you have a discord? I would like to chat with you outside of a PR

**Comment by wissehes** [comment]
Thanks for your help! Yes, my Discord is TheChicken#9522

**Pull request merged**
